name: build-major

on:
  workflow_dispatch:

env:
  DOCKER_HUB_IMAGE_NAME: skipero/neat-ci
  IMAGE_NAME: keenrouter/neat-ci

jobs:
  plan:
    name: Generate the build matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.result }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6

      - uses: actions/github-script@v8
        id: set-matrix
        with:
          # the token is not needed for the script running
          github-token: empty
          script: return await require('./.github/scripts/generate-major-node-matrix.js')({github, context, core})
        env:
          source-image: library/node
          target-image: ${{ env.DOCKER_HUB_IMAGE_NAME }}
          tags-map: |
            1:trixie-slim

  build:
    name: Build the docker image (${{ matrix.targetTag }})
    needs: 
      - plan
    if: ${{ fromJSON(needs.plan.outputs.matrix).include[0] }} 
    # docs <https://bit.ly/2YHHXXs>
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.plan.outputs.matrix) }}
      #  include:
      #    - {tag: foo, platforms: 'platform/one,platform/two/v2'}
    steps:
      - uses: actions/checkout@v6
      - uses: docker/setup-qemu-action@v4
      - uses: docker/setup-buildx-action@v4

      - uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v7 
        if: ${{ !env.ACT || vars.LOCAL_PUSH }}
        # gh act -W ./github/workflows/build-major.yml --secret-file .env --var-file .env --var LOCAL_PUSH
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: ${{ matrix.platforms }}
          build-args: "FROM_IMAGE=debian:${{ matrix.sourceTag }}"
          tags: |
            ${{ env.DOCKER_HUB_IMAGE_NAME }}:${{ matrix.targetTag }}
            ${{ env.DOCKER_HUB_IMAGE_NAME }}:latest
            ghcr.io/${{ env.IMAGE_NAME }}:${{ matrix.targetTag }}
            ghcr.io/${{ env.IMAGE_NAME }}:latest
  
  allgood:
    name: All previous steps are OK
    needs:
      - plan
      - build
    runs-on: ubuntu-
    steps: []

          
